Getting routes

In [1]:
import pandas as pd
from collections import OrderedDict

# Import package numpy for numeric computing
import numpy as np

# Import package matplotlib for visualisation/plotting
import matplotlib.pyplot as plt

#For showing plots directly in the notebook
%matplotlib inline

In [2]:
df = pd.read_csv('route40CLEAN.csv') # change for route (possibly programm to run all
df.columns = ['Timestamp', 'LineID', 'Direction', 'JourneyPatternID', 'TimeFrame', 'VehicleJourneyID', 'Operator', 'Congestion', 'Longitude', 'Latitude', 'Delay', 'BlockID', 'VehicleID', 'StopID', 'AtStop', 'Date']
df.head(1)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Longitude,Latitude,Delay,BlockID,VehicleID,StopID,AtStop,Date
0,1352184864000000,40.0,0,null,2012-11-06,2510,HN,0,-6.260334,53.353134,0,40207,33279,null,0,2012-11-06 06:54:24

In [3]:
df.shape

(1176673, 16)

In [4]:
#df= df.dropna( how='any', subset = ['JourneyPatternID', 'StopID'])
df=df[df.JourneyPatternID != 'null']

In [5]:
df=df[df.StopID != 'null']
df.head(1)

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Longitude,Latitude,Delay,BlockID,VehicleID,StopID,AtStop,Date
2,1352184864000000,40.0,0,00400001,2012-11-06,6408,HN,0,-6.346193,53.342491,-395,40104,33278,2712,0,2012-11-06 06:54:24

In [6]:
df.shape

(971563, 16)

In [7]:
df= df.dropna( how='any', subset = ['JourneyPatternID', 'StopID'])
df['JourneyPatternID'].unique()

array(['00400001', '040D0002', '00401001', '040D1002', '040B1001',
       '040B0001', '00400002', '040D1001', '040D0001', '00400004',
       '00401002', '00680004', '040B0002'], dtype=object)

In [8]:
df2 = df[df['JourneyPatternID'] == '00400001' ]

In [9]:
#df1['StopID'].unique()

In [10]:
#df2 = df1[df1['AtStop'] == 1]
#not necessary or accurate if not normally at stop

In [11]:
#df2['StopID'].unique()

In [12]:
#df2['StopID'].value_counts()

In [13]:
#df2.VehicleJourneyID.value_counts()
df2['Date'] = pd.to_datetime(df2['Date'])

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [14]:
df_mon = df2[df2['Date'].dt.dayofweek == 0]
df_tues = df2[df2['Date'].dt.dayofweek == 1]
df_wed = df2[df2['Date'].dt.dayofweek == 2]
df_thurs = df2[df2['Date'].dt.dayofweek == 3]
df_fri = df2[df2['Date'].dt.dayofweek == 4]
df_sat = df2[df2['Date'].dt.dayofweek == 5]
df_sun = df2[df2['Date'].dt.dayofweek == 6]

In [35]:

df_mon6 = df_mon[df_mon['Date'].dt.hour >= 6]

In [36]:
df_mon6 = df_mon6[df_mon6['Date'].dt.hour <= 23]

In [43]:
jid = df_mon6['VehicleJourneyID'].unique()

In [48]:
for j in jid:
    df_temp = df_mon[df_mon['VehicleJourneyID'] == j ]
    temp1 = df_temp.head(1)
    c = int(temp1['Timestamp'])
    stops = df_temp.StopID.unique() 

    for i in stops:
        temp = df_temp[df_temp['StopID'] == i ].head(1)
        StopID = int(temp['StopID'])
        b = int(temp['Timestamp'])
        seconds = (b-c)/1000000
        df_mon['Seconds'] = seconds
   # print ("StopID and time in seconds")
   # print (data)

C:\Users\Daniel\Anaconda3\lib\site-packages\ipykernel\__main__.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

KeyboardInterrupt:

In [49]:
df_mon

,Timestamp,LineID,Direction,JourneyPatternID,TimeFrame,VehicleJourneyID,Operator,Congestion,Longitude,Latitude,Delay,BlockID,VehicleID,StopID,AtStop,Date,Seconds
264888,1352703346000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.265009,53.352009,-293,40106,33140,52,0,2012-11-12 06:55:46,3625.0
264890,1352703346000000,40.0,0,00400001,2012-11-12,6420,HN,0,-6.318534,53.339706,-624,40105,33222,1947,0,2012-11-12 06:55:46,3625.0
264893,1352703348000000,40.0,0,00400001,2012-11-12,6408,HN,0,-6.349093,53.342190,-338,40104,33162,2712,0,2012-11-12 06:55:48,3625.0
264895,1352703348000000,40.0,0,00400001,2012-11-12,6429,HN,0,-6.288801,53.379753,-332,40101,38065,7471,0,2012-11-12 06:55:48,3625.0
264901,1352703350000000,40.0,0,00400001,2012-11-12,6434,HN,0,-6.310645,53.397247,-264,40102,38066,1523,0,2012-11-12 06:55:50,3625.0
264917,1352703362000000,40.0,0,00400001,2012-11-12,6412,HN,1,-6.398035,53.353668,-629,40103,33145,4411,0,2012-11-12 06:56:02,3625.0
264924,1352703364000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.264970,53.351986,-275,40106,33140,52,0,2012-11-12 06:56:04,3625.0
264926,1352703364000000,40.0,0,00400001,2012-11-12,6429,HN,0,-6.288801,53.379753,-312,40101,38065,7471,0,2012-11-12 06:56:04,3625.0
264927,1352703364000000,40.0,0,00400001,2012-11-12,6420,HN,0,-6.320109,53.339378,-624,40105,33222,1947,0,2012-11-12 06:56:04,3625.0
264929,1352703366000000,40.0,0,00400001,2012-11-12,6408,HN,0,-6.351800,53.342144,-338,40104,33162,2712,0,2012-11-12 06:56:06,3625.0
264938,1352703370000000,40.0,0,00400001,2012-11-12,6434,HN,0,-6.311052,53.396042,-280,40102,38066,1523,0,2012-11-12 06:56:10,3625.0
264949,1352703384000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.264634,53.353931,-275,40106,33140,52,0,2012-11-12 06:56:24,3625.0
264951,1352703384000000,40.0,0,00400001,2012-11-12,6408,HN,0,-6.352105,53.342140,-338,40104,33162,2712,0,2012-11-12 06:56:24,3625.0
264953,1352703384000000,40.0,0,00400001,2012-11-12,6412,HN,1,-6.398035,53.353668,-609,40103,33145,4411,0,2012-11-12 06:56:24,3625.0
264955,1352703384000000,40.0,0,00400001,2012-11-12,6429,HN,0,-6.288801,53.379753,-292,40101,38065,7471,0,2012-11-12 06:56:24,3625.0
264962,1352703391000000,40.0,0,00400001,2012-11-12,6434,HN,0,-6.310674,53.395615,-280,40102,38066,1524,1,2012-11-12 06:56:31,3625.0
264977,1352703403000000,40.0,0,00400001,2012-11-12,6412,HN,1,-6.398035,53.353668,-589,40103,33145,4411,0,2012-11-12 06:56:43,3625.0
264980,1352703407000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.262909,53.353962,-257,40106,33140,261,1,2012-11-12 06:56:47,3625.0
264982,1352703407000000,40.0,0,00400001,2012-11-12,6408,HN,0,-6.352835,53.342163,-315,40104,33162,2655,1,2012-11-12 06:56:47,3625.0
264984,1352703407000000,40.0,0,00400001,2012-11-12,6429,HN,0,-6.287752,53.379169,-292,40101,38065,7471,0,2012-11-12 06:56:47,3625.0
264990,1352703411000000,40.0,0,00400001,2012-11-12,6434,HN,0,-6.311007,53.395111,-280,40102,38066,1524,0,2012-11-12 06:56:51,3625.0
265005,1352703423000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.262190,53.353352,-257,40106,33140,261,0,2012-11-12 06:57:03,3625.0
265011,1352703423000000,40.0,0,00400001,2012-11-12,6412,HN,1,-6.398035,53.353668,-569,40103,33145,4411,0,2012-11-12 06:57:03,3625.0
265015,1352703425000000,40.0,0,00400001,2012-11-12,6408,HN,0,-6.355678,53.342381,-315,40104,33162,2655,0,2012-11-12 06:57:05,3625.0
265016,1352703425000000,40.0,0,00400001,2012-11-12,6429,HN,0,-6.287653,53.378902,-292,40101,38065,1533,1,2012-11-12 06:57:05,3625.0
265018,1352703425000000,40.0,0,00400001,2012-11-12,6420,HN,0,-6.321648,53.341507,-663,40105,33222,2643,0,2012-11-12 06:57:05,3625.0
265024,1352703430000000,40.0,0,00400001,2012-11-12,6434,HN,0,-6.311660,53.394123,-280,40102,38066,1525,1,2012-11-12 06:57:10,3625.0
265032,1352703444000000,40.0,0,00400001,2012-11-12,6420,HN,0,-6.324853,53.341816,-663,40105,33222,2643,0,2012-11-12 06:57:24,3625.0
265037,1352703444000000,40.0,0,00400001,2012-11-12,6424,HN,0,-6.262807,53.353874,-219,40106,33140,261,0,2012-11-12 06:57:24,3625.0
265040,1352703444000000,40.0,0,00400001,2012-11-12,6412,HN,1,-6.398035,53.353668,-549,40103,33145,4411,0,2012-11-12 06:57:24,3625.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972108,1353970803000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.389536,53.347626,-402,40004,33291,2674,0,2012-11-26 23:00:03,3625.0
972115,1353970811000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.324853,53.341816,-1047,40005,33399,2643,0,2012-11-26 23:00:11,3625.0
972118,1353970825000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.392180,53.347763,-402,40004,33291,2674,0,2012-11-26 23:00:25,3625.0
972127,1353970834000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.327359,53.342072,-1047,40005,33399,2643,0,2012-11-26 23:00:34,3625.0
972134,1353970844000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.395570,53.347866,-402,40004,33291,2675,1,2012-11-26 23:00:44,3625.0
972138,1353970850000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.329525,53.342239,-1047,40005,33399,2644,0,2012-11-26 23:00:50,3625.0
972141,1353970852000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.303637,53.396946,273,40010,33294,1548,0,2012-11-26 23:00:52,3625.0
972153,1353970872000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.333259,53.342972,-1047,40005,33399,2644,0,2012-11-26 23:01:12,3625.0
972159,1353970883000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.397995,53.346981,-402,40004,33291,2124,1,2012-11-26 23:01:23,3625.0
972166,1353970889000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.334540,53.343239,-1026,40005,33399,2709,0,2012-11-26 23:01:29,3625.0
972168,1353970891000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.306517,53.396637,273,40010,33294,1548,0,2012-11-26 23:01:31,3625.0
972173,1353970903000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.398157,53.346077,-402,40004,33291,2124,0,2012-11-26 23:01:43,3625.0
972180,1353970911000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.338674,53.342506,-1026,40005,33399,2709,0,2012-11-26 23:01:51,3625.0
972181,1353970911000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.306974,53.398319,257,40010,33294,1549,0,2012-11-26 23:01:51,3625.0
972189,1353970926000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.398231,53.345596,-376,40004,33291,2125,1,2012-11-26 23:02:06,3625.0
972194,1353970934000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.309078,53.398056,257,40010,33294,1549,0,2012-11-26 23:02:14,3625.0
972198,1353970944000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.398402,53.344299,-376,40004,33291,2125,0,2012-11-26 23:02:24,3625.0
972202,1353970950000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.345552,53.342472,-1045,40005,33399,2712,1,2012-11-26 23:02:30,3625.0
972203,1353970952000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.309579,53.397938,257,40010,33294,1523,1,2012-11-26 23:02:32,3625.0
972204,1353970965000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.398455,53.343849,-359,40004,33291,2126,0,2012-11-26 23:02:45,3625.0
972215,1353970973000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.348015,53.342384,-1045,40005,33399,2712,0,2012-11-26 23:02:53,3625.0
972216,1353970973000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.310859,53.396919,257,40010,33294,1523,0,2012-11-26 23:02:53,3625.0
972224,1353970983000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.398817,53.342327,-359,40004,33291,2126,0,2012-11-26 23:03:03,3625.0
972227,1353970989000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.351221,53.342167,-1045,40005,33399,2712,0,2012-11-26 23:03:09,3625.0
972231,1353970991000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.310813,53.395988,257,40010,33294,1523,0,2012-11-26 23:03:11,3625.0
972241,1353971012000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.352835,53.342163,-1045,40005,33399,2655,1,2012-11-26 23:03:32,3625.0
972242,1353971012000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.311499,53.394367,257,40010,33294,1524,0,2012-11-26 23:03:32,3625.0
972252,1353971030000000,40.0,0,00400001,2012-11-26,5727,CD,0,-6.355514,53.342369,-1045,40005,33399,2655,0,2012-11-26 23:03:50,3625.0
972253,1353971030000000,40.0,0,00400001,2012-11-26,5763,CD,0,-6.311882,53.392971,257,40010,33294,1525,0,2012-11-26 23:03:50,3625.0
972260,1353971042000000,40.0,0,00400001,2012-11-26,5717,CD,0,-6.399855,53.339703,-339,40004,33291,2128,1,2012-11-26 23:04:02,3625.0

In [20]:
df_tues['StopID'].unique()

array(['2712', '1533', '1549', '1942', '261', '2674', '2675', '1943',
       '1523', '1944', '1534', '2124', '1535', '2125', '270', '2655',
       '1524', '2126', '1536', '1525', '2128', '1537', '1526', '186',
       '2668', '6080', '2129', '1945', '335', '838', '2672', '1946', '839',
       '1947', '4797', '1585', '2673', '7473', '840', '1586', '2642',
       '2206', '2643', '4592', '2681', '4521', '4798', '1587', '4691',
       '2682', '2644', '4539', '4796', '2709', '841', '4690', '2711',
       '1935', '4411', '4937', '1606', '1547', '2127', '1548', '1607',
       '2656', '1937', '49', '1608', '1938', '1609', '4715', '1939',
       '1610', '7471', '51', '1940', '1941', '52', '4795', '2710', '1989'], dtype=object)

In [21]:
df_wed['StopID'].unique()

array(['1549', '2206', '1533', '1947', '2129', '841', '1523', '49', '4798',
       '1534', '2642', '2643', '4797', '51', '7473', '1535', '1524',
       '2674', '2644', '1525', '2709', '2681', '2675', '1536', '2710',
       '4691', '1526', '2124', '1537', '2712', '52', '4796', '2125',
       '2126', '6080', '186', '838', '2128', '4592', '4411', '2655', '839',
       '1586', '261', '840', '4937', '1587', '2656', '2668', '1548',
       '4539', '270', '2672', '2673', '1606', '4715', '1607', '1608',
       '1609', '2682', '1610', '4690', '335', '7471', '2127', '1585',
       '4521', '4795', '1935', '1937', '1938', '1939', '1940', '1941',
       '1942', '1943', '1944', '1945', '1946', '2711', '1547', '4799'], dtype=object)

In [22]:
stops = df2.StopID.unique()

In [23]:
#df2['StopID'] = df2['StopID'].astype(int)
stops

array(['2712', '1533', '1549', '1942', '261', '2674', '2675', '1943',
       '1523', '1944', '1534', '2124', '1535', '2125', '270', '2655',
       '1524', '2126', '1536', '1525', '2128', '1537', '1526', '186',
       '2668', '6080', '2129', '1945', '335', '838', '2672', '1946', '839',
       '1947', '4797', '1585', '2673', '7473', '840', '1586', '2642',
       '2206', '2643', '4592', '2681', '4521', '4798', '1587', '4691',
       '2682', '2644', '4539', '4796', '2709', '841', '4690', '2711',
       '1935', '4411', '4937', '1606', '1547', '2127', '1548', '1607',
       '2656', '1937', '49', '1608', '1938', '1609', '4715', '1939',
       '1610', '7471', '51', '1940', '1941', '52', '4795', '2710', '2679',
       '2680', '1989', '7', '4688', '7510', '2696', '279', '2676', '4799'], dtype=object)

In [24]:
#As dicts aren't ordered, and order of stops is important OrderedDict is necessary
data = OrderedDict()
temp1 = df2.head(1)
c = int(temp1['Timestamp'])

for i in stops:
    temp = df2[df2['StopID'] == i ].head(1)
    StopID = int(temp['StopID'])
    b = int(temp['Timestamp'])
    seconds = (b-c)/1000000
    data[StopID] = seconds
print ("StopID and time in seconds")
print (data)
    
#get average time from stops to 
#new_df.append(data, ignore_index=True)

StopID and time in seconds
OrderedDict([(2712, 0.0), (1533, 0.0), (1549, 2.0), (1942, 6.0), (261, 6.0), (2674, 6.0), (2675, 27.0), (1943, 27.0), (1523, 43.0), (1944, 47.0), (1534, 57.0), (2124, 66.0), (1535, 78.0), (2125, 86.0), (270, 88.0), (2655, 100.0), (1524, 102.0), (2126, 104.0), (1536, 119.0), (1525, 143.0), (2128, 147.0), (1537, 157.0), (1526, 182.0), (186, 196.0), (2668, 200.0), (6080, 205.0), (2129, 205.0), (1945, 207.0), (335, 227.0), (838, 237.0), (2672, 241.0), (1946, 248.0), (839, 258.0), (1947, 268.0), (4797, 268.0), (1585, 282.0), (2673, 282.0), (7473, 284.0), (840, 297.0), (1586, 303.0), (2642, 307.0), (2206, 321.0), (2643, 325.0), (4592, 325.0), (2681, 325.0), (4521, 327.0), (4798, 342.0), (1587, 344.0), (4691, 346.0), (2682, 364.0), (2644, 366.0), (4539, 382.0), (4796, 387.0), (2709, 407.0), (841, 419.0), (4690, 421.0), (2711, 425.0), (1935, 425.0), (4411, 442.0), (4937, 462.0), (1606, 462.0), (1547, 481.0), (2127, 501.0), (1548, 501.0), (1607, 521.0), (2656, 526.0), (1937, 526.0), (49, 538.0), (1608, 562.0), (1938, 587.0), (1609, 603.0), (4715, 624.0), (1939, 628.0), (1610, 642.0), (7471, 663.0), (51, 677.0), (1940, 728.0), (1941, 765.0), (52, 777.0), (4795, 806.0), (2710, 2382.0), (2679, 286958.0), (2680, 466901.0), (1989, 625307.0), (7, 992079.0), (4688, 1073568.0), (7510, 1499660.0), (2696, 1591102.0), (279, 1595468.0), (2676, 1680045.0), (4799, 1927440.0)])

In [25]:
#As dicts aren't ordered, and order of stops is important OrderedDict is necessary
data = OrderedDict()
temp1 = df2.head(1)
c = int(temp1['Timestamp'])

for i in stops:
    temp = df2[df2['StopID'] == i ].head(1)
    StopID = int(temp['StopID'])
    b = int(temp['Timestamp'])
    seconds = (b-c)/1000000
    data[StopID] = seconds
print ("StopID and time in seconds")
print (data)
    

#new_df.append(data, ignore_index=True)

StopID and time in seconds
OrderedDict([(2712, 0.0), (1533, 0.0), (1549, 2.0), (1942, 6.0), (261, 6.0), (2674, 6.0), (2675, 27.0), (1943, 27.0), (1523, 43.0), (1944, 47.0), (1534, 57.0), (2124, 66.0), (1535, 78.0), (2125, 86.0), (270, 88.0), (2655, 100.0), (1524, 102.0), (2126, 104.0), (1536, 119.0), (1525, 143.0), (2128, 147.0), (1537, 157.0), (1526, 182.0), (186, 196.0), (2668, 200.0), (6080, 205.0), (2129, 205.0), (1945, 207.0), (335, 227.0), (838, 237.0), (2672, 241.0), (1946, 248.0), (839, 258.0), (1947, 268.0), (4797, 268.0), (1585, 282.0), (2673, 282.0), (7473, 284.0), (840, 297.0), (1586, 303.0), (2642, 307.0), (2206, 321.0), (2643, 325.0), (4592, 325.0), (2681, 325.0), (4521, 327.0), (4798, 342.0), (1587, 344.0), (4691, 346.0), (2682, 364.0), (2644, 366.0), (4539, 382.0), (4796, 387.0), (2709, 407.0), (841, 419.0), (4690, 421.0), (2711, 425.0), (1935, 425.0), (4411, 442.0), (4937, 462.0), (1606, 462.0), (1547, 481.0), (2127, 501.0), (1548, 501.0), (1607, 521.0), (2656, 526.0), (1937, 526.0), (49, 538.0), (1608, 562.0), (1938, 587.0), (1609, 603.0), (4715, 624.0), (1939, 628.0), (1610, 642.0), (7471, 663.0), (51, 677.0), (1940, 728.0), (1941, 765.0), (52, 777.0), (4795, 806.0), (2710, 2382.0), (2679, 286958.0), (2680, 466901.0), (1989, 625307.0), (7, 992079.0), (4688, 1073568.0), (7510, 1499660.0), (2696, 1591102.0), (279, 1595468.0), (2676, 1680045.0), (4799, 1927440.0)])